### ISSUE TITLE
Routing issue in searching by day vs searching by id? 

### ISSUE THREAD

**Issue by SiouxsieAsylum** [SiouxsieAsylum/datetime#1]
So I'm attempting to both look for events by id and look for events by day. I've learned that whichever route handler came first, `/:id` or `/:day` will be activated regardless of what the key of the `req.param` object is. I tried setting up a conditional, but it still left the request hanging and I'm not sure why. I'm assuming I need some kind of middleware? But I'm not clear on how I would formulate that kind of function. Any ideas?

The non-functional get request so you can see what I am aiming to do:
```javascript
// whichever of these two controllers come first will run because the routes can't automatically tell the datatype. gotta make sure the right controller is being invoked

eventRouter.get("/:id", (req,res) => {
  if ((req.params.id).includes("-")){
    console.log("in the day")
    eventController.findByDay;
  } else {
    console.log("in the show")
    eventController.show;
  };
})
``` 

This is in routes/event-routes.js lines 12-20.

Thank you!

**Comment by jsm13** [comment]
The problem here is that `/:id` and `/:day` are going to match the exact same routes so whichever is defined second won't ever get hit. You need some way to distinguish between the routes. I think easiest option might be a query string on the index. So if the query string has a `day` (or something like that, maybe a range) value provided, then a constraint gets added to the SQL lookup (goes from all events to all events within some time window)
```
// request: GET "/events?day=<timestamp>"
eventRouter.get('/', (req, res) => {
  if (req.query.day) {
    // restricted query
  } else {
    // general query
  }
}
```

Could also do this like the way we did in the birds exercise with a path like `/events/day/<day>` but I think the query string is a nice way to handle it because it really is just a index request with more conditions on it.
